// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hijqvncgmmletbptxgch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpanF2bmNnbW1sZXRicHR4Z2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTY2MjEsImV4cCI6MjA1ODg3MjYyMX0.GJLb4yJwlCQaM1_SJavgzAJo_agLP-cND2DA_LwLJX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);